version: '3.8'

services:
  backend:
    build: 
      context: ./backend-contabilidad
    container_name: backend-unapec
    image: contabilidad-unapec-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend-contabilidad
    container_name: frontend-unapec
    image: contabilidad-unapec-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
